# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Welcome
email: tphddevdrop@gmail.com
description: > # this means to ignore newlines until "# baseurl:"
  MargoCSS is a lightweight responsive CSS framework (~19KB) that provides you
  with useful components and helper classes for building your site.

twitter_username: jekyllrb
github_username:  jekyll

permalink: /articles/:title.html

paginate: 4
paginate_path: "/posts/page:num"

# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, bower_component, exec]
gems: 
  - jekyll-paginate 
  - jekyll-autoprefixer

autoprefixer:
  browsers:
  - > 5%

#Development-Settings
# url: "http://localhost:3000" # the base hostname & protocol for your site
# baseurl: "" # the subpath of your site, e.g. /my-furries

#Production-Settings
baseurl: "" 
url: "https://margocss.github.io" # the base hostname & protocol for your site


#ENV
